name: Work_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inst_dep
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Lint_flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: tst_nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
